name: Imposer CLI Workflow

on:
  push:
    branches:
      - main

jobs:
  imposter-cli-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Imposer CLI
        run: |
          curl -L https://raw.githubusercontent.com/gatehill/imposter-cli/main/install/install_imposter.sh | bash -

      - name: Generate Imposter Specification File
        run: imposter scaffold ${{ env.OPENAPI_FILE_PATH }} --output imposter-spec.yaml

      - name: Upload to AWS S3 Bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Upload to S3
        run: aws s3 cp imposter-spec.yaml s3://your-s3-bucket/path/to/imposter-spec/

  update-lambda-counter:
    runs-on: ubuntu-latest
    needs: imposter-cli-job

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Get Current Counter Value
        id: get-counter
        run: |
          COUNTER=$(aws lambda get-function-configuration \
            --function-name your-lambda-function-name \
            --query 'Environment.Variables.COUNTER' \
            --output text)
          echo "::set-output name=COUNTER::$COUNTER"
        env:
          AWS_REGION: your-aws-region

      - name: Increment Counter
        run: |
          NEW_COUNTER=$((COUNTER + 1))
          aws lambda update-function-configuration \
            --function-name your-lambda-function-name \
            --environment "Variables={COUNTER=$NEW_COUNTER}"
        env:
          COUNTER: ${{ steps.get-counter.outputs.COUNTER }}
          AWS_REGION: your-aws-region
