plugin: openapi
path: /
resources:
- method: GET
  path: /forecast
  response:
    statusCode: 200
- method: GET
  path: /weather
  response:
    statusCode: 200
- method: GET
  path: /todos
  response:
    statusCode: 201
specFile: weather.yaml
